const mongoose = require('mongoose');

const accordionSchema = new mongoose.Schema({
    'Ano da Publicação': String,
    Contencioso: String,
    Data: String,
    'Data de Entrada': String,
    'Data do Acordão': String,
    Decisão: String,
    'Decisão Texto Integral': String,
    Descritores: String,
    'Indicações Eventuais': String,
    'Jurisprudência Nacional': String,
    'Legislação Nacional': String,
    Magistrado: String,
    'Meio Processual': String,
    'Nº Convencional': String,
    'Nº Processo/TAF': String,
    'Nº do Documento': String,
    Objecto: String,
    Privacidade: String,
    Processo: String,
    Recorrente: String,
    Recorrido: Array,
    'Referência a Doutrina': String,
    Relator: String,
    Secção: String,
    Sumário: String,
    'Texto Integral': String,
    Tribunal: String,
    'Tribunal Recurso': String,
    Votação: String,
    tribunal: String,
    url: String,
    'Área Temática': Array,
    'Mais Informação': String,
});

const myDB = mongoose.connection.useDb('JusticeDB');
module.exports = myDB.model('accordion', accordionSchema);
