const mongoose = require('mongoose');

const accordionSchema = new mongoose.Schema({
    '1ª Pág. de Publicação do Acordão': String,
    Acordão: String,
    'Ano da Publicação': String,
    Apenso: String,
    Apêndice: String,
    Autor: String,
    Constituição: String,
    Contencioso: String,
    Data: String,
    'Data Dec. Recorrida': String,
    'Data da Decisão': String,
    'Data de Entrada': String,
    'Data do Acordão': String,
    'Data do Apêndice': String,
    'Data do Diário da República': String,
    Decisão: String,
    'Decisão Texto Integral': String,
    'Declaração de Voto': String,
    Descritores: String,
    'Disponível na JTCA': String,
    Espécie: String,
    'Indicações Eventuais': String,
    'Jurisprudência Constitucional': String,
    'Jurisprudência Estrangeira': String,
    'Jurisprudência Internacional': String,
    'Jurisprudência Nacional': String,
    'Juízo ou Secção': String,
    'Legislação Comunitária': String,
    'Legislação Estrangeira': String,
    'Legislação Nacional': String,
    Magistrado: String,
    'Meio Processual': String,
    'Normas Apreciadas': String,
    'Normas Declaradas Inconst.': String,
    'Normas Julgadas Inconst.': String,
    'Normas Suscitadas': String,
    'Nº Convencional': String,
    'Nº Processo/TAF': String,
    'Nº do Boletim do M.J.': String,
    'Nº do Diário da República': String,
    'Nº do Documento': String,
    'Nº do Volume': String,
    'Nº Único do Processo': String,
    Objecto: String,
    Observações: String,
    'Outra Jurisprudência': String,
    'Outras Publicações': String,
    'Peça Processual': String,
    Privacidade: String,
    Processo: String,
    'Processo no Tribunal Recorrido': String,
    'Processo no Tribunal Recurso': String,
    'Página do Boletim do M.J.': String,
    'Página do Diário da República': String,
    'Página do Volume': String,
    Reclamações: String,
    Recorrente: String,
    Recorrido: Array,
    Recurso: String,
    Recursos: String,
    'Recusa Aplicação': String,
    'Referência Processo': String,
    'Referência Publicação 1': String,
    'Referência a Doutrina': String,
    'Referência a Pareceres': String,
    'Referência de Publicação': String,
    'Referências Internacionais': String,
    Relator: String,
    Requerente: String,
    Requerido: String,
    Réu: String,
    'Sub-Secção': String,
    Sumário: String,
    'Série do Diário da República': String,
    Tema: String,
    'Texto Integral': String,
    'Texto das Cláusulas Abusivas': String,
    'Tipo de Ação': String,
    'Tipo de Contrato': String,
    Tribunal: String,
    'Tribunal 1ª instância': String,
    'Tribunal Recorrido': String,
    'Tribunal Recurso': String,
    'Volume dos Acordãos do T.C.': String,
    Votação: String,
    'Voto Vencido': String,
    tribunal: String,
    url: String,
    'Área Temática': Array,
});

const myDB = mongoose.connection.useDb('JusticeDB');
module.exports = myDB.model('accordion', accordionSchema);
